### ISSUE TITLE
NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by GnaXi** [Awesome-Technologies/synapse-admin#18]
I've just setup synapse-admin in a docker container and I am able to login with my account.
However, as soon as I log in I am presented with a red warning message at the bottom of the page stating:
"NetworkError when attempting to fetch resource."

I'm running version 1.11.1 of Synapse and I've made sure that my account is admin.
Any suggestions or ideas as to what could be wrong?

**Comment by awesome-manuel** [comment]
Can you have a look in the developer console of your browser which HTTP request actually failed?

**Comment by GnaXi** [comment]
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://matrix.domain.tld/_synapse/admin/v2/users?from=0&guests=true&limit=10. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://matrix.domain.tld/_synapse/admin/v2/users?from=0&guests=true&limit=10. (Reason: CORS request did not succeed).

These are what I'm seeing in the console.

**Comment by awesome-manuel** [comment]
That means you need to setup CORS headers for your synapse instance properly or serve synapse-admin from the same domain.

**Comment by GnaXi** [comment]
As this isn't included in a standard installation of synapse, I guess it would be worth mentioning in your readme of synapse-admin? :)

**Comment by awesome-manuel** [comment]
It's actually the same for Riot-Web. Can you access your synapse instance from riot.im web client?

**Comment by GnaXi** [comment]
Yes, Riot-Web works just fine.

**Comment by awesome-manuel** [comment]
Are there different CORS headers for the client and admin interfaces? You can check using the web developer tools.

**Comment by GnaXi** [comment]
Hmm.. Even though Riot-Web is working just fine, I'm getting the same type of error in the console, when loading it:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://matrix.domain.tld/.well-known/matrix/client. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

**Comment by awesome-manuel** [comment]
Riot-web can work without the .well-known address but synapse-admin currently not. See also #16.

**Comment by GnaXi** [comment]
Do you happen to know where to find that in a standard installation of synapse?
I used the Prebuild package for Debian/Ubuntu:
https://github.com/matrix-org/synapse/blob/master/INSTALL.md#prebuilt-packages

**Comment by awesome-manuel** [comment]
Actually this should be fixed: https://github.com/matrix-org/synapse/issues/4593
Do you run your synapse behind a reverse proxy?

**Comment by GnaXi** [comment]
> I'm also using a reverse proxy (apache). Would you by chance know where I would have to add it?

Indeed, which I mentioned earlier :P

**Comment by awesome-manuel** [comment]
Google is your friend: https://github.com/matrix-org/synapse/blob/master/docs/ACME.md

For nginx users, add the following line to your existing server block:

```
location /.well-known/acme-challenge {
    proxy_pass http://localhost:8009;
}
```
For Apache, add the following to your existing webserver config:

`ProxyPass /.well-known/acme-challenge http://localhost:8009/.well-known/acme-challenge`

**Comment by GnaXi** [comment]
I've added the following to my existing apache reverse proxy configuration:
ProxyPass /.well-known http://localhost:8009/.well-known

But unfortunately the issue remains the same.

**Comment by awesome-manuel** [comment]
I'm sorry, but this is now out of scope for synapse-admin. Please ask the synapse guys how to configure this correctly.

**Comment by squarepupil** [comment]
> 
> 
> Google is your friend: https://github.com/matrix-org/synapse/blob/master/docs/ACME.md
> 
> For nginx users, add the following line to your existing server block:
> 
> ```
> location /.well-known/acme-challenge {
>     proxy_pass http://localhost:8009;
> }
> ```
> 
> For Apache, add the following to your existing webserver config:
> 
> `ProxyPass /.well-known/acme-challenge http://localhost:8009/.well-known/acme-challenge`
> 
> Of course not only for the acme-challenge but everything under .well-kown

I am having the same issues as @GnaXi and am not finding any documentation that has helped me resolve the problem.

If I understand correctly, synapse-admin requires the synapse homeserver to have ACME enabled (i.e., the homeserver can provision certificates). The documentation you link to states that synapse will not support that feature anymore after June 2020. What is the recommendation for synapse-admin to be functional absent synapse's ACME support?

**Comment by awesome-manuel** [comment]
Latest master works without HTTPS.

**Comment by ggogel** [comment]
Synapse-Admin stopped working for me with the errors `CORS Missing Allow Origin` and `NS_ERROR_DOM_BAD_URI`. All paths are forwarded correctly and clients work fine. Either an update in synapse or synapse-admin broke it.

**Comment by Weuxel** [comment]
This still happens now matter the CORS Config.

**Comment by ggogel** [comment]
Currently it's working again for me. No idea though what fixed it.

**Comment by ThyMYthOS** [comment]
@Weuxel this issue is closed. If you have a specific issue that is caused by synapse-admin please open a new ticket and provide as much information as you can (logs from synapse, logs from your reverse proxy, reverse proxy configuration, logs from web developer console).

**Comment by awesome-manuel** [comment]
@Weuxel this issue is closed. If you have a specific issue that is caused by synapse-admin please open a new ticket and provide as much information as you can (logs from synapse, logs from your reverse proxy, reverse proxy configuration, logs from web developer console).
